# Name for the devops role that will be created
devopsRoleName: ${self:custom.settings.globalNamespace}-DevopsRole

# Name for the role associated with workflow loop runner lambda
workflowLoopRunnerRoleName: ${self:custom.settings.namespace}-WorkflowLoopRunner

# The IAM role arn for the workflow loop runner lambda
workflowLoopRunnerRoleArn: 'arn:aws:iam::${self:custom.settings.awsAccountInfo.awsAccountId}:role/${self:custom.settings.workflowLoopRunnerRoleName}'

#External ID (AWS account ID of the main account) used to assume the Devops Role
externalId: ${self:custom.settings.awsAccountInfo.awsAccountId}