AWSTemplateFormatVersion: 2010-09-09
Description: Service-Workbench-on-AWS ALB for RStudio IDE
Parameters:
  Namespace:
    Type: String
    Description: An environment name that will be prefixed to resource names
  VPC:
    Description: The VPC in which the EC2 instance will reside
    Type: AWS::EC2::VPC::Id
  ALBSubnet1:
    Description: The VPC subnet 1 in which the Application load Balancer will reside
    Type: AWS::EC2::Subnet::Id
  ALBSubnet2:
    Description: The VPC subnet 2 in which the Application load Balancer will reside
    Type: AWS::EC2::Subnet::Id
  LoadBalancerType:
    Description: Type of ALB (internal or internet-facing)
    Type: String
  ACMSSLCertARN:
    Type: String
    Description: The ARN of the AWS Certificate Manager SSL Certificate to associate with the Load Balancer
  IsAppStreamEnabled:
    Type: String
    AllowedValues: [true, false]
    Description: Is AppStream enabled for this workspace
  AppStreamSG:
    Type: String
    Description: AppStream Security Group ID
  PublicRouteTableId:
    Type: String
    Description: Public Route Table ID
  LoggingBucket:
    Type: String
    Description: Bucket for ELB Logs

Resources:
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            ContentType: "text/plain"
            MessageBody: "Forbidden"
            StatusCode: "403"
      LoadBalancerArn:
        Ref: ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-2016-08
      Certificates:
        - CertificateArn: !Ref ACMSSLCertARN
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref Namespace
      Scheme: !Ref LoadBalancerType
      Subnets:
        - Ref: ALBSubnet1
        - Ref: ALBSubnet2
      SecurityGroups:
        - Ref: ALBSecurityGroup
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          IpProtocol: "-1"
      GroupDescription: ALB SecurityGroup
      VpcId: !Ref VPC
Outputs:
  LoadBalancerArn:
    Description: ARN of Application Load Balancer
    Value: !Ref ApplicationLoadBalancer
  ALBDNSName:
    Description: DNS Name of Application Load Balancer
    Value: !GetAtt ApplicationLoadBalancer.DNSName
  ListenerArn:
    Description: ARN of Application Load Balancer Listener
    Value: !Ref ALBListener
  ALBSecurityGroupId:
    Description: Security Group of Application Load Balancer Listener
    Value: !Ref ALBSecurityGroup